# .travis.yml
sudo: required
dist: trusty
os: linux

language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache

php:
  - 7.1

services:
  - docker

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine --allow-unauthenticated
  - docker version

  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
- docker-compose up --build -d
- docker ps -a

script:
  - mkdir -p coverage/
  - docker-compose up --exit-code-from php-cli

after_success:
  # enable logging
  - travis_retry php vendor/bin/php-coveralls -v
  - docker-compose down
  
notifications:
  email: false