FROM php:7.1-cli

LABEL maintainer="mohammadfouladgarphp@gmail.com"

RUN pecl install xdebug

RUN apt-get update -y && \
    apt-get install -y autoconf pkg-config libssl-dev libmcrypt-dev mysql-client zip unzip git && \
    docker-php-ext-install -j$(nproc) pdo pdo_mysql zip && docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/ \
    && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer


WORKDIR /filter


ADD entrypoint.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh

ENTRYPOINT [ "/usr/local/bin/run.sh" ]
